### ISSUE TITLE
Sequential timeframe collapse

### ISSUE THREAD

**Issue by agubarev** [amv-dev/yata#20]
Hi,

I've found something that could possibly be an issue with https://docs.rs/yata/latest/yata/core/trait.Sequence.html#method.collapse_timeframe

When using collapse_timeframe(n, true) on a sequence i.e., `Vec<Candle>`, it collapses each subsequent pair, for example, given an input sequence [1, 2, 3, 4, 5, 6] candles, it produces a following output:

[(1, 2), (2, 3), (3, 4), (4, 5), (5, 6)] instead of [(1, 2), (3, 4), (5, 6)], please correct me if I'm wrong and this is working as intended. 

I'll now try the https://docs.rs/yata/latest/yata/methods/struct.CollapseTimeframe.html with chunks of the original sequence.

P.S. You're developing a beautiful library.

**Comment by amv-dev** [comment]
Hello! Thank you.
Did you try to use `collapse_timeframe` with `continuous` argument set to `false`? Looks like this is what you are looking for.

**Comment by agubarev** [comment]
No, but now I understand what I got wrong about `continuous`, I misunderstood your idea and didn't __see it__ in the code last night. It does exactly what I had to write yesterday for my purpose, so now sticking back to yours. Thank you.
