### ISSUE TITLE
Refactor: Bench requires running nightly / beta.

### ISSUE THREAD

**Issue by dandxy89** [amv-dev/yata#35]
Compiling and executing the benchmarks requres a non-stable version of Rust. 

Would you open to migration to [`divan`](https://docs.rs/divan/latest/divan/) or [`criterion`](https://github.com/bheisler/criterion.rs) so they can be run on stable?

**Comment by amv-dev** [comment]
To be honest, I don't think this question matters right now. There are much more important improvements to be done. But somewhere in the future this may be done.
