### ISSUE TITLE
What is new in version 0.7?

### ISSUE THREAD

**Issue by olehbozhok** [amv-dev/yata#44]
It would be great to add notice of what is new in version 0.7

**Comment by amv-dev** [comment]
There is nothing new in v0.7, but `HeikinAshi` internal structure was changed which will cause incompatibility with older version when deserializing structure. That's why I decided to increase minor version.

**Comment by olehbozhok** [comment]
I got it, thanks

**Comment by olehbozhok** [comment]
I got it, thanks
