### ISSUE TITLE
understand MA

### ISSUE THREAD

**Issue by cometta** [amv-dev/yata#49]
i saw the example look like below, what is the purpose to repeating inputing the first value?
```
// SMA of length=3
let mut sma = SMA::new(3, &1.0).unwrap(); // may i know is &1.0 the first value same as next line?

sma.next(&1.0);  // in SMA::new(), aren't we already input first value?
sma.next(&2.0);

assert_eq!(sma.next(&3.0), 2.0);
assert_eq!(sma.next(&4.0), 3.0);
```

**Comment by amv-dev** [comment]
Hello.
You are totally correct. First value in `SMA::new(3, &1.0)` is the same value as in the next line.
Yes, there is no reason to provide first input again. It will not change internal state of a MA. The only reason to provide first input again is to get resulting value (and use it somewhere else).

**Comment by 6qat** [comment]
What's the second argument of SMA::new function?

**Comment by amv-dev** [comment]
> What's the second argument of SMA::new function?

Again, it's just the very first value of time series you want to process.
